### ISSUE TITLE
The module does not work on Puppet 3.4.3

### ISSUE THREAD

**Issue by nl0pvm** [locp/gitssh#3]
When I try use the accounts on module on a server running Puppet 3.4.3, the module failed with this error message:

Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter purge_ssh_keys at /etc/puppet/environments/production/modules/gitssh/manifests/init.pp:27 
It is found that the module tries to create a user resource, passing the parameter purge_ssh_keys (manifests/init.pp:25). By commenting out that line, it could be run successfully.
The purge_ssh_keys on user type is introduced in 3.6.0 https://docs.puppetlabs.com/puppet/3.6/reference/release_notes.html#feature-purging-unmanaged-ssh-authorized-keys.

Maybe, it is better to check the version of puppet before using user type to purge the ssh keys: https://ask.puppetlabs.com/question/6640/warning-the-package-types-allow_virtual-parameter-will-be-changing-its-default-value-from-false-to-true-in-a-future-release/?answer=9525#post-id-9525

**Comment by dallinb** [comment]
Hi,

I'll ensure the version check is put in and get a patch out as soon as possible.

Ben

**Comment by dallinb** [comment]
Reproducing the problem on Travis (https://travis-ci.org/locp/gitssh/jobs/161608611)

**Comment by dallinb** [comment]
Need to fix checks when `STRICT_VARIABLES="yes"`.

**Comment by dallinb** [comment]
Peter,

I believe that this is now fixed and will be release 0.1.2.  Please let me know if this is not the case.  There are also some more changes being bundled into this, please see the change log when this makes it onto the Puppet forge.

 Dank je wel!
